version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Copenhagen
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    commit-message:
      prefix: chore
      include: scope
    cooldown:
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    ignore:
      - dependency-name: google-cloud-firestore
        versions:
          - ">=2.28.0, <2.29.0"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Copenhagen
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    commit-message:
      prefix: chore
      include: scope
    cooldown:
      default-days: 3
    groups:
      github-actions:
        patterns:
          - "*"
